# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KenOrtiz
email: kenortiznj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is still a work in progress. At this time, it is being used to host markdown presentation slides.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kenortiz.github.io" # the base hostname & protocol for your site
github_username:  kenortiz

# Build settings
markdown: kramdown
